# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install Maui
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore MauiInsights/MauiInsights.csproj
    
    - name: Build
      run: dotnet build MauiInsights/MauiInsights.csproj --no-restore
    
    - name: Pack
      run: dotnet pack MauiInsights/MauiInsights.csproj
