name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Install Maui
      run: dotnet workload install maui
        
    - name: Restore dependencies
      run: dotnet restore MauiInsights/MauiInsights.csproj 
    
    - name: Build
      run: dotnet build MauiInsights/MauiInsights.csproj --no-restore
    
    - name: Pack
      run: dotnet pack MauiInsights/MauiInsights.csproj -p:PackageVersion='${{ github.job }}''

    - name: Push
      run: dotnet nuget push MauiInsights/MauiInsights/bin/Release/MauiInsights.${{ github.job }}.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json
